on:
  push: 
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Install dependencies Main
        working-directory: ./Main
        run: npm install
      - name: Run Tests
        run: npm run test
